# Generated by Django 4.0.6 on 2022-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_note_addresses_remove_note_name_note_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_c',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_d',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='note_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='self_d',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
